# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-02 03:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_text', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date requested')),
                ('request_count', models.PositiveIntegerField(default=1, verbose_name='count')),
            ],
        ),
    ]
